- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Restart k3s
  ansible.builtin.systemd_service:
    name: "{{ 'k3s' if inventory_hostname in groups['k3s_server'] else 'k3s-agent' }}"
    state: restarted
